version: '3.8'
services:
  db-postgres:
    image: postgres:14-alpine
    restart: always
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
